### ISSUE TITLE
rtdetr  dont support onnx.GatherElements opr in AXOPS

### ISSUE THREAD

**Issue by qin-yuhao** [AXERA-TECH/pulsar2-docs#5]
oot@qyh-B760M-POWER-DDR4:/data# pulsar2 build --input rtdetr_r18vd_5x_coco_objects365_from_paddle.onnx  --config rtdetr_config.json --output_dir rtdetr/r18_test/ --npu_mode NPU3 --output_name rtdetr_r18_msda.axmodel
2024-04-03 18:28:17.664 | WARNING  | yamain.command.build:fill_default:255 - apply default quant configuration to ['images']
2024-04-03 18:28:17.664 | WARNING  | yamain.command.build:fill_default:269 - apply default input processor configuration to ['images']
2024-04-03 18:28:17.665 | WARNING  | yamain.command.build:fill_default:320 - ignore images csc config because of src_format is AutoColorSpace or src_format and tensor_format are the same
Building onnx ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━  40% 0:00:01
Traceback (most recent call last):
  File "<frozen yamain.common.error>", line 11, in wrapper
  File "<frozen yamain.command.build>", line 631, in optimize_onnx
  File "<frozen yamain.command.load_model>", line 633, in optimize_onnx_model
  File "<frozen frontend.parsers.onnx_parser>", line 71, in parse_onnx_model
  File "<frozen frontend.parsers.onnx_parser>", line 144, in parse_onnx_model_proto
  File "<frozen opset.oprdef>", line 330, in Opr
KeyError: 'dont support onnx.GatherElements opr in AXOPS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "</opt/pulsar2/yamain/main.py>", line 4, in <module>
  File "<frozen yamain.main>", line 282, in <module>
  File "<frozen yamain.main>", line 210, in pulsar2
  File "<frozen yamain.main>", line 143, in wrapper
  File "<frozen yamain.common.error>", line 17, in wrapper
  File "<frozen yamain.command.build>", line 191, in build_error
  File "<frozen yamain.common.error>", line 11, in wrapper
  File "<frozen yamain.command.build>", line 439, in build
  File "<frozen yamain.common.error>", line 17, in wrapper
  File "<frozen yamain.common.error>", line 67, in error_func
yamain.common.error.CodeException: (<ErrorCode.OnnxOptimizationError: 13>, KeyError('dont support onnx.GatherElements opr in AXOPS'))

**Comment by qin-yuhao** [comment]
https://zhuanlan.zhihu.com/p/683445595 , i follow this blog step by step,but stil wrong
